### PR TITLE
fix: create new capsule project when not found

### LINKED ISSUE #486: Failed to create new contract in the new project created by kuai init
```
$ kuai contract new --name hello
New contract "hello"
error: No such file or directory (os error 2)
Error: Command failed: cd /home/ian/codebase/kuai-hello-dapp/contract && capsule new-contract hello --template rust
```

Fixed by creating the directory contract/contracts manually

### PR DESCRIPTION
**Pull request by PainterPuppets**
If the project was not created by the `kuai init` command. the `kuai-cli` will report an error when running the `contract` command, this pr will detect & initialize the `capsule` before running the `contract` command.

reslove: https://github.com/ckb-js/kuai/issues/486

### CODE REVIEW

File: packages/core/src/builtin-tasks/contract.ts [hunk 1]
```diff
@@ -496,16 +496,30 @@ subtask('contract:sign-message')
...
   }
 
-  return path.join(path.dirname(userConfigPath), 'contract')
+  const workspacePath = (() => {
+    if (config.contract?.workspace) {
+      return path.join(path.dirname(userConfigPath), config.contract?.workspace)
+    }
+
+    return path.join(path.dirname(userConfigPath), 'contract')
+  })()
```
Comment (Keith-CY) [inline packages/core/src/builtin-tasks/contract.ts]: It can be simplified as

```js
const workspacePath = path.join(path.dirname(userConfigPath), config.contract?.workspace ?? 'contract')
```

**Comment by Keith-CY** [comment]
Tests should be added

**Review by Daryl-L — APPROVED** [review]

**Comment by Keith-CY** [comment]
Any update of the tests to be added

**Comment by PainterPuppets** [comment]
added e2e-test

**Comment by Keith-CY** [comment]
CI failed

**Review by yanguoyu — APPROVED** [review]
