### PR TITLE
fix: Resource binding can bind one of lock or type, or bind lock and type

### LINKED ISSUE #504: Some problem in developing the sUDT manager
1. The consideration for transaction information was overlooked. In the development of the sUDT management platform, a requirement arose to manage the transaction history, necessitating the synchronization of on-chain transactions. However, within Kuai, there is no built-in functionality for syncing transactions. Consequently, it becomes necessary to independently implement the synchronization of transaction records in the script and store them in the database.

2. The development experience with Kuai and Lumos in tandem is quite problematic. Take, for example, the generation of an sUDT, where Lumos provides the function `issueToken`. However, this function lacks the capability to pass cell information as the issuer. This renders the cell information synchronized by Kuai somewhat redundant. Regardless of whether Kuai provides cell information in the Model, Lumos needs to re-query through script or other account data, such as the `payFee` function. To enhance the Kuai development experience, it is essential for Lumos, as a framework for Nervos, to make certain adaptations.

### PR DESCRIPTION
**Pull request by yanguoyu**
This PR is used to fix https://github.com/ckb-js/kuai/issues/504#issuecomment-1756929777.

### CODE REVIEW

File: packages/io/src/chain-source/nervos.ts [hunk 1]
```diff
@@ -20,25 +23,43 @@ export class NervosChainSource implements ChainSource {
     return header.number
   }
 
-  getAllLiveCellsWithWitness = async (
-    lockScript: Script,
-    typeScript?: Script | undefined,
-    startBlock?: BI,
-    endBlock?: BI,
-  ) => {
+  getAllLiveCellsWithWitness = async (lockScript?: Script, typeScript?: Script, startBlock?: BI, endBlock?: BI) => {
```
Comment (Keith-CY) [inline packages/io/src/chain-source/nervos.ts]: Two objects with named fields would be clearer, otherwise `undefined` should be passed in explicitly.

```ts
getAllLiveCellsWithWitnesses = async (scripts: Partial<Record<'lock' | 'type', Script>>, blockRange?: Partial<Record<'start' | 'end', BI>> => {}
```

File: packages/io/src/chain-source/nervos.ts [hunk 2]
```diff
@@ -20,25 +23,43 @@ export class NervosChainSource implements ChainSource {
...
+        withData: true,
+      }
+    } else if (typeScript) {
+      scriptFilterOption = {
+        script: typeScript,
+        scriptType: 'type',
+        withData: true,
+      }
+    }
+    if (!scriptFilterOption) throw new Error('One of lock script and type script is required at least')
```
Comment (Keith-CY) [inline packages/io/src/chain-source/nervos.ts]:
```suggestion
    if (!scriptFilterOption) throw new Error('One of lock script or type script is required at least')
```

**Review by Keith-CY — APPROVED** [review]

**Comment by Keith-CY** [comment]
Please have a review @Daryl-L @PainterPuppets

**Review by Daryl-L — APPROVED** [review]
